package com.lms.common.domain;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** Table {@code ReportAudit} — entity REPORT_AUDIT (1:N GENERATED BY): one row per report generated. */
@Entity
@Table(name = "ReportAudit")
@Getter
@Setter
@NoArgsConstructor
public class ReportAudit {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ReportAuditID")
    @Setter(AccessLevel.NONE)
    private Integer reportAuditId;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "RequestedByUserID", nullable = false)
    private AppUser requestedBy;

    @Enumerated(EnumType.STRING)
    @Column(name = "ReportType", nullable = false, length = 30)
    private ReportType reportType;

    /** The filters used, as JSON text; CK_ReportAudit_FilterIsJson rejects invalid JSON. */
    @Column(name = "FilterJson")
    private String filterJson;

    @Column(name = "GeneratedAt", nullable = false, updatable = false)
    private LocalDateTime generatedAt;

    @PrePersist
    void onCreate() {
        if (generatedAt == null) {
            generatedAt = DbTime.now();
        }
    }
}
